# **NUMPY**
*Numpy is a Linear Algebra Library for Python*

In [ ]:
import numpy as np

## **NUMPY ARRAYS - 1D VECTORS/ 2D MATRICES**

In [ ]:
my_list = [1, 2, 3]
my_array = np.array(my_list) # Type casting the python list to a 1D Numpy array
print(my_list)
print(my_array)
print(type(my_list), type(my_array))
# It is of type numpy.ndarray

[1, 2, 3]
[1 2 3]
<class 'list'> <class 'numpy.ndarray'>


In [ ]:
# Similiarly 2d matrices can be typecasted from list of lists
my_list_2d = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]
my_mat_2d = np.array(my_list_2d)
print(my_list_2d)
print(my_mat_2d)
print(type(my_list_2d), type(my_mat_2d))
# It is of type numpy.ndarray

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'> <class 'numpy.ndarray'>


In [ ]:
## Generating with numpy methods
arr1 = np.arange(0, 11, 2)
# Creates an array in certain range start and stop (exclusive) and a step
arr1

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
## Generate arrays of all zeros
arr0_1d = np.zeros(3) # 3 is the number of zeros
arr0_2d = np.zeros((2, 3)) # 2x3 of zeros
arr0_3d = np.zeros((3, 3, 3)) # 3, 3, 3
print(arr0_1d)
print(arr0_2d)
print(arr0_3d)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
## Similiarly an array full of ones can be created
arr_ones = np.ones((2, 3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
## LINSPACE - Returns evenly spaced intervals over a specified intervals
## Different from arange
np.linspace(0, 5, 10) # start, stop, third number
# means gives 10 evenly spaced numbers from 5 to 10

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.linspace(1, 100, 5) # 5 evenly spaced numbers from 1 to 100

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
## ARRAYS OF RANDOM NUMBERS -
# rand - creates array of given shape and random samples from 0 to 1
np.random.rand(5)

array([0.34493918, 0.67359324, 0.07999802, 0.67908893, 0.58113241])

In [ ]:
np.random.rand(2, 5) # 2x5 matrix

array([[0.80290785, 0.27523534, 0.40034605, 0.62553352, 0.67346674],
       [0.21912696, 0.75780444, 0.82075742, 0.25057052, 0.2451655 ]])

In [ ]:
## To get integers we use randint
# randint returns random numbers from low to high
np.random.randint(1, 100)

50

In [ ]:
np.random.randint(10, 30, 5) # size 1x5

array([19, 13, 24, 16, 27])

In [ ]:
np.random.randint(1000, 3000, (3, 5)) # 3x5

array([[1520, 1361, 1492, 2057, 1090],
       [1930, 2183, 2960, 2824, 1898],
       [1590, 2496, 1535, 1958, 2390]])

### **RESHAPE ARRAY**

In [ ]:
arr1 = np.arange(1, 26)
arr2 = np.random.randint(0, 50, 10)

In [ ]:
arr1.reshape(5, 5) # as there are 25 elements there

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# number of rowx x number of columns = no of total elements
arr2.reshape(2, 5)

array([[ 9, 21, 39, 43, 47],
       [43,  2, 28, 48, 11]])

In [ ]:
## TO GET MAX AND MIN AND etc
print(arr2.max())
print(arr2.min())
print(arr2.argmax()) # gets the index
print(arr2.argmin()) # gets the index

48
2
8
6


In [ ]:
# FEW MORE
## to get shape and dimensions
arr_new = np.random.randint(10, 30, (5,3))
print(arr_new.ndim) # 5x3
print(arr_new.shape)

2
(5, 3)


In [ ]:
## To get the datatype of array
arr_new.dtype

dtype('int64')

## **NUMPY INDEXING AND SELECTION**

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# To get a single value at index -
arr[8]

np.int64(8)

In [ ]:
# to get values by slicing
arr[1: 4]
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
[int(x) for x in list(arr[:])]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
arr[0 : 5] = 100 # Means elements of that range is 100
# This is broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
## Grabbing from 2d array
arr2d[1, 2] # 30

np.int64(30)

In [ ]:
arr2d[2, 1] # 40

np.int64(40)

In [ ]:
# Grabbing a part
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

## **NUMPY OPERATIONS**

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr*5 / arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

## **NUMPY PRACTICE**

In [ ]:
## Creating ndarrays
myList = [1, 2, 3, 4, 5]
myArr = np.array(myList)
myArr

array([1, 2, 3, 4, 5])

In [ ]:
myList2 = [[1, 2, 3], [4, 5, 6]]
myArr2 = np.array(myList2)
myArr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
myArr2.size, myArr2.shape

(6, (2, 3))

In [ ]:
myArr2.ndim, myArr2.dtype

(2, dtype('int64'))

In [ ]:
## Creatnting arrays of zeros
z1 = np.zeros(5) # of size 1x5
z1

array([0., 0., 0., 0., 0.])

In [ ]:
z2 = np.zeros((5, 7)) # of size 5 x 7

In [ ]:
z3 = np.empty((2, 3)) # This sets data as garbage values. Not zeros
z3

array([[2.23891166e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [ ]:
arr1 = np.array([1, 3, 5, 7, 9], dtype=np.float64)
arr1

array([1., 3., 5., 7., 9.])

In [ ]:
arr_1 = np.random.randint(10, 100, (3, 5))
arr_1

array([[59, 17, 37, 19, 87],
       [52, 48, 81, 35, 98],
       [64, 75, 78, 43, 79]])

In [ ]:
arr_2 = np.arange(1, 16)
arr_2 = arr_2.reshape((3, 5))
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr_1 + arr_2

array([[ 60,  19,  40,  23,  92],
       [ 58,  55,  89,  44, 108],
       [ 75,  87,  91,  57,  94]])

In [ ]:
arr_1 * arr_2

array([[  59,   34,  111,   76,  435],
       [ 312,  336,  648,  315,  980],
       [ 704,  900, 1014,  602, 1185]])

In [ ]:
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7 ,8, 9],
                  [10, 11, 12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print(arr3.shape)
print(arr3.size)
print(arr3.ndim)

(2, 2, 3)
12
3


In [ ]:
arr3[0, 0, 0]

np.int64(1)

In [ ]:
arr3[1, 0, 2]

np.int64(9)

In [ ]:
arr3[0, 0, 1:]

array([2, 3])

In [ ]:
## TRANSPOSING
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr.T.T

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T.T == np.arange(15).reshape((3, 5))

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
arr = np.random.randn(6, 3)
arr

array([[-0.34221669, -1.80953412,  0.02288617],
       [-0.31584701,  0.55712448, -0.61015554],
       [-0.66962939, -0.12183339, -0.13434815],
       [ 0.40709612,  0.29240706,  1.24741507],
       [ 0.42653332,  1.06367872, -1.33872055],
       [-1.69672359,  0.24704832,  0.54756548]])

In [ ]:
arr = np.arange(20, 31)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
np.sqrt(arr)

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558])

In [ ]:
np.exp(arr)

array([4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13])